Controllers/ControlController.cs
using AMDng.Models;
using Dapper;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AMDng.Controllers
{
    public class ControlController : Controller
    {
        readonly string _DBConn = System.Web.Configuration.WebConfigurationManager.ConnectionStrings["DBConnection"].ConnectionString;

        public ActionResult Draw()
        {
            if (Session["AMD"] == null) Response.Redirect("~/Control/Login");
            return View();
        }

        public ActionResult Index()
        {
            if (Session["AMD"] == null) return Redirect("~/Control/Login");
            return PartialView();
        }

        public ActionResult Login()
        {
            if (Session["AMD"] != null) return Redirect("~/Control");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string Password)
        {
            if (Password == "AMDVerifier")
            {
                Session["AMD"] = true;
                return Redirect("~/Control");
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return Redirect("~/Control/Login");
        }

        /// <summary>
        /// 查詢兌換紀錄
        /// </summary>
        /// <param name="Model">AMD</param>
        /// <param name="SDate">日期開始區間</param>
        /// <param name="EDate">日期結束區間</param>
        /// <returns></returns>
        public ActionResult Query(AMD Model, DateTime? SDate, DateTime? EDate)
        {
            try
            {
                using (SqlConnection dbConn = new SqlConnection(_DBConn))
                {
                    string strSQL = "SELECT * FROM AMD WHERE ID > 0 AND Type=@Type";
                    if (!string.IsNullOrWhiteSpace(Model.UName)) strSQL += " AND UName LIKE N'%'+@UName+'%'";
                    if (!string.IsNullOrWhiteSpace(Model.UPhone)) strSQL += " AND UPhone=@UPhone";
                    if (!string.IsNullOrWhiteSpace(Model.UEmail)) strSQL += " AND UEmail=@UEmail";
                    if (!string.IsNullOrWhiteSpace(Model.UInvoice)) strSQL += " AND UInvoice=@UInvoice";
                    if (!string.IsNullOrWhiteSpace(Model.UCPUType)) strSQL += " AND UCPUType=@UCPUType";
                    if (!string.IsNullOrWhiteSpace(Model.UBuyStore)) strSQL += " AND UBuyStore=@UBuyStore";
                    if (!string.IsNullOrWhiteSpace(Model.USeagate)) strSQL += " AND USeagate=@USeagate";
                    if (!string.IsNullOrWhiteSpace(Model.UTForce)) strSQL += " AND UTForce=@UTForce";
                    if (Model.CState != null) strSQL += " AND CState=@CState";
                    if (SDate != null) strSQL += $" AND InsertDateTime>='{SDate.Value.ToString("yyyy/MM/dd 00:00:00")}'";
                    if (EDate != null) strSQL += $" AND InsertDateTime<'{EDate.Value.AddDays(1).ToString("yyyy/MM/dd 00:00:00")}'";

                    return Json(dbConn.Query<AMD>(strSQL, Model).ToList(), JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json(new List<AMD>(), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 審核
        /// </summary>
        /// <param name="Model">AMD</param>
        /// <returns></returns>
        public ActionResult Verify(AMD Model)
        {
            try
            {
                using (SqlConnection dbConn = new SqlConnection(_DBConn))
                {
                    string strSQL = "UPDATE AMD SET CState=@CState,CReason=@CReason,CAnotherReason=@CAnotherReason WHERE ID=@ID";

                    dbConn.Open();
                    using (SqlTransaction trade = dbConn.BeginTransaction())
                    {
                        dbConn.Execute(strSQL, Model, transaction: trade);
                        trade.Commit();
                    }

                    return Json(true, JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 匯出
        /// </summary>
        /// <param name="Model">AMD</param>
        /// <param name="SDate">日期開始區間</param>
        /// <param name="EDate">日期結束區間</param>
        /// <returns></returns>
        public ActionResult Export(AMD Model, DateTime? SDate, DateTime? EDate)
        {
            try
            {
                using (SqlConnection dbConn = new SqlConnection(_DBConn))
                {
                    string strSQL = "SELECT * FROM AMD WHERE ID > 0 AND Type=@Type";
                    if (!string.IsNullOrWhiteSpace(Model.UName)) strSQL += " AND UName LIKE N'%'+@UName+'%'";
                    if (!string.IsNullOrWhiteSpace(Model.UPhone)) strSQL += " AND UPhone=@UPhone";
                    if (!string.IsNullOrWhiteSpace(Model.UEmail)) strSQL += " AND UEmail=@UEmail";
                    if (!string.IsNullOrWhiteSpace(Model.UInvoice)) strSQL += " AND UInvoice=@UInvoice";
                    if (!string.IsNullOrWhiteSpace(Model.UCPUType)) strSQL += " AND UCPUType=@UCPUType";
                    if (!string.IsNullOrWhiteSpace(Model.UBuyStore)) strSQL += " AND UBuyStore=@UBuyStore";
                    if (!string.IsNullOrWhiteSpace(Model.USeagate)) strSQL += " AND USeagate=@USeagate";
                    if (!string.IsNullOrWhiteSpace(Model.UTForce)) strSQL += " AND UTForce=@UTForce";
                    if (Model.CState != null) strSQL += " AND CState=@CState";
                    if (SDate != null) strSQL += $" AND InsertDateTime>='{SDate.Value.ToString("yyyy/MM/dd 00:00:00")}'";
                    if (EDate != null) strSQL += $" AND InsertDateTime<'{EDate.Value.AddDays(1).ToString("yyyy/MM/dd 00:00:00")}'";

                    List<AMD> result = dbConn.Query<AMD>(strSQL, Model).ToList();

                    string strGuid = Guid.NewGuid() + ".csv";

                    using (var file = new StreamWriter(Path.Combine(Server.MapPath("~/export"), strGuid), false, System.Text.Encoding.UTF8))
                    {
                        file.WriteLine($"姓名,連絡電話,E-mail,發票號碼,CPU序號,CPU型號,購買店家,Seagate SSD全系列,T-Force RGB系列記憶體,申請時間");
                        foreach (var item in result)
                        {
                            file.WriteLine($"{item.UName},=\"{item.UPhone}\",{item.UEmail},{item.UInvoice ?? "無"},{item.UCPUSN ?? "無"},{item.UCPUType ?? "無"},{item.UBuyStore ?? "無"},{item.USeagate ?? "無購買"},{item.UTForce ?? "無購買"},{item.InsertDateTime.ToString("yyyy/MM/dd HH:mm")}");
                        }
                    }

                    return Json("/export/" + strGuid, JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Views/Shared/_CLayout.cshtml
<!DOCTYPE html>
<html ng-app="amd">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AMD 兌換後臺管理</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/behind")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Control">AMD 兌換後臺管理</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("登出", "Logout", "Control")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer class="text-right">
            <p>&copy; @DateTime.Now.Year - AMD 兌換後臺管理</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/behind")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="amd">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>AMD 兌換活動網站</title>
    <link rel="shortcut icon" href="https://www.amd.com/themes/custom/amd/favicon.ico" type="image/vnd.microsoft.icon">
<!-- Global site tag (gtag.js) - Google Ads: 632880635 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-632880635"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-632880635');
</script>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/front")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrap">
        <header id="header-w">
            <div class="header">
                <div id="carousel-vision" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="~/images/AMD-YES-Faith.jpg">
                        </div>
                        <div class="item">
                            <img src="~/images/B550_Banner.jpg">
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-vision" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">上一張</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-vision" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">下一張</span>
                    </a>
                </div>
            </div>
        </header>
        <div id="container-w">
            <div class="container-d">
                <div class="main_content">
                    <div class="nav-tabs">
                        <ul class="nav-justified">
                            <li role="presentation" ng-class="{ 'active': page === 'faith' }" data-target="#carousel-vision" data-slide-to="0"><a href="/#!/faith">打造你的電競區</a></li>
                            <li role="presentation" ng-class="{ 'active': page === 'b550' }" data-target="#carousel-vision" data-slide-to="1"><a href="/#!/b550">AMD B550 給你裝B！</a></li>
                            <li role="presentation" ng-class="{ 'active': page === 'progress' }" data-target="#carousel-vision" data-slide-to="2"><a href="/#!/progress">查詢進度</a></li>
                        </ul>
                    </div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    <div id="partner" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">配合經銷商</h4>
                </div>
                <div class="modal-body">
                    <table class="rwd-table">
                        <tbody>
                            <tr>
                                <th colspan="5">連鎖通路</th>
                            </tr>

                            <tr>
                                <td>原價屋<br>(全省門市)</td>
                                <td>三井電腦<br>(全省門市)</td>
                                <td>欣亞數位<br>(全省門市)</td>
                                <td>順發電腦<br>(全省門市)</td>
                                <td>虹優科技<br>(全省門市)</td>
                            </tr>
                            <tr>
                                <th colspan="5">北部</th>
                            </tr>

                            <tr>
                                <td>健宏電腦</td>
                                <td>澺狄企業</td>
                                <td>歆宇科技	</td>
                                <td>崇時科技</td>
                                <td>昇鼎科技</td>
                            </tr>
                            <tr>
                                <td>德總電腦</td>
                                <td>立曜電腦</td>
                                <td>紐頓電子</td>
                                <td>廣大數位</td>
                                <td>易飛資訊</td>
                            </tr>
                            <tr>
                                <td>泓達電腦</td>
                                <td>崇宏科技</td>
                                <td>安辰科技</td>
                                <td>慶聲資訊</td>
                                <td>台灣奇茂資訊</td>
                            </tr>
                            <tr>
                                <td>霐道電腦</td>
                                <td>星曜科技</td>
                                <td>時邁電腦</td>
                                <td>銘睿科技</td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <th colspan="5">中部</th>
                            </tr>

                            <tr>
                                <td>駿太科技</td>
                                <td>凌傑資訊	</td>
                                <td>宏晉科技</td>
                                <td>漢碩電腦</td>
                                <td>仕鉑電腦</td>
                            </tr>
                            <tr>
                                <td>洋基電腦</td>
                                <td>久昇資訊</td>
                                <td>麻吉電腦</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <th colspan="5">南部</th>
                            </tr>

                            <tr>
                                <td>德源電腦</td>
                                <td>秉鑫電腦</td>
                                <td>洋宏資訊</td>
                                <td>華挺資訊</td>
                                <td>維碁電腦</td>
                            </tr>
                            <tr>
                                <td>協新科技</td>
                                <td>星鋐國際</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <th colspan="5">電商網站</th>
                            </tr>

                            <tr>
                                <td>PChome 24h	</td>
                                <td>MoMo</td>
                                <td>Yahoo!</td>
                                <td>iPCE</td>
                                <td>&nbsp;</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">關閉</button>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/front")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>